### PR TITLE
fix: package.json & yarn.lock to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-HANDLEBARS-1056767
- https://snyk.io/vuln/SNYK-JS-HANDLEBARS-1279029
- https://snyk.io/vuln/SNYK-JS-POSTCSS-1090595
- https://snyk.io/vuln/SNYK-JS-POSTCSS-1255640

### CODE REVIEW

**Comment by Rudloff** [comment]
The css-loader update seems to break the style:
image

**Comment by KristjanESPERANTO** [comment]
That's strange. I am withdrawing the version increase for "CSS Loader", so that you can apply the other changes.

But at some point we should take a closer look at it.

**Comment by Rudloff** [comment]
OK then, if this does not contain breaking changes anymore, it can go on master.

**Comment by Rudloff** [comment]
Wait, I think having handlebars in the direct dependencies is a mistake.
0e3f44c874598bb3e75d257e557cece2a2aa7daa added it but we don't use it directly.
(Also, it seems we don't even need it anymore since 0ac26c6cfb8590e844a1f58d1472c2b99ce0f529.)

I removed it in 29d7d7b46e41aed66acc247718f092b425ec5ac3.

**Pull request closed without merging**
